### ISSUE TITLE
EKS to EKS cluster

### ISSUE THREAD

**Issue by wheestermans31** [awslabs/aws-kubernetes-migration-factory#2]
Can this tool be used for EKS to EKS cluster migration too?

**Comment by vasarobi** [comment]
@wheestermans31 - Sorry for the late response.  We have tested GKE to EKS migrations, but should work for EKS to EKS and there might some things that might not work as expected. In that case you will have to slightly modify the code and use it.

**Comment by vasarobi** [comment]
We would like to hear your feedback after testing.
